variables:
  - name: installation
    required: true
  - name: stage
    required: false
    default: none
  - name: app
    required: true
layers:
  - id: defaults
    path:
      directory: default
      required: true
    values:
      path:
        directory: ""
      configMap:
        name: config.yaml
        required: true
    templates:
      path:
        directory: apps/<< app >>
        required: true
      configMap:
        name: configmap-values.yaml.template
        required: true
        values:
          merge:
            strategy: ConfigMapsInLayerOrder
      secret:
        name: secret-values.yaml.template
        required: false
        values:
          merge:
            strategy: ConfigMapsAndSecretsInLayerOrder
  - id: default-stages
    path:
      directory: default/stages
      required: false
    values:
      path:
        directory: << stage >>
        required: false
      configMap:
        name: config.yaml
        required: false
    templates:
      path:
        directory: << stage >>/apps/<< app >>
        required: false
      configMap:
        name: configmap-values.yaml.template
        required: false
        values:
          merge:
            strategy: ConfigMapsInLayerOrder
      secret:
        name: secret-values.yaml.template
        required: false
        values:
          merge:
            strategy: SecretsInLayerOrder
  - id: stages
    path:
      directory: stages
      required: false
    values:
      path:
        directory: << stage >>
        required: false
      configMap:
        name: config.yaml
        required: false
    templates:
      path:
        directory: << stage >>/apps/<< app >>
        required: false
      configMap:
        name: configmap-values.yaml.template
        required: false
        values:
          merge:
            strategy: ConfigMapsInLayerOrder
      secret:
        name: secret-values.yaml.template
        required: false
        values:
          merge:
            strategy: SecretsInLayerOrder
  - id: management-cluster
    path:
      directory: installations/<< installation >>
      required: true
    values:
      path:
        directory: ""
      configMap:
        name: config.yaml.patch
        required: true
      secret:
        name: secret.yaml
        required: true
    templates:
      path:
        directory: apps/<< app >>
        required: false
      configMap:
        name: configmap-values.yaml.patch
        required: false
        values:
          merge:
            strategy: ConfigMapsInLayerOrder
      secret:
        name: secret-values.yaml.patch
        required: false
        values:
          merge:
            strategy: SameTypeFromCurrentLayer
includes:
  - id: include
    function:
      name: include
    path:
      directory: include
      required: true
    extension: .yaml.template
  - id: include-self
    function:
      name: includeSelf
    path:
      directory: include-self
      required: false
    extension: .yaml.template
